config/routes.rb
Rails.application.routes.draw do

  	resources :favourites_recipes
  	resources :user_recipes
  	resources :categories
	devise_for :users
	resources :recipes

	resources :recipes do
	  put :favourite, on: :member
	end

	root "recipes#index"
end

app/models/favourites_recipe.rb
class FavouritesRecipe < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipe
end

app/controllers/favourites_recipes_controller.rb
class FavouritesRecipesController < ApplicationController
  before_action :set_favourites_recipe, only: [:show, :edit, :update, :destroy]

  # GET /favourites_recipes
  # GET /favourites_recipes.json
  def index
    @favourites_recipes = FavouritesRecipe.all
  end

  # GET /favourites_recipes/1
  # GET /favourites_recipes/1.json
  def show
  end

  # GET /favourites_recipes/new
  def new
    @favourites_recipe = FavouritesRecipe.new
  end

  # GET /favourites_recipes/1/edit
  def edit
  end

  # POST /favourites_recipes
  # POST /favourites_recipes.json
  def create
    @favourites_recipe = FavouritesRecipe.new
    @favourites_recipe.user_id = current_user.id
    @favourites_recipe.recipe_id = params[:recipe_id]
    respond_to do |format|
      if @favourites_recipe.save
        format.html { redirect_to @favourites_recipe, notice: 'Favourites recipe was successfully created.' }
        format.json { render :show, status: :created, location: @favourites_recipe }
      else
        format.html { render :new }
        format.json { render json: @favourites_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites_recipes/1
  # PATCH/PUT /favourites_recipes/1.json
  def update
    respond_to do |format|
      if @favourites_recipe.update(favourites_recipe_params)
        format.html { redirect_to @favourites_recipe, notice: 'Favourites recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourites_recipe }
      else
        format.html { render :edit }
        format.json { render json: @favourites_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites_recipes/1
  # DELETE /favourites_recipes/1.json
  def destroy
    @favourites_recipe.destroy
    respond_to do |format|
      format.html { redirect_to favourites_recipes_url, notice: 'Favourites recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourites_recipe
      @favourites_recipe = FavouritesRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourites_recipe_params
      params.require(:favourites_recipe).permit(:recipe_id)
    end
end

app/helpers/favourites_recipes_helper.rb
module FavouritesRecipesHelper
end

app/views/favourites_recipes/_form.html.erb
<%= form_for(@favourites_recipe) do |f| %>
  <% if @favourites_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favourites_recipe.errors.count, "error") %> prohibited this favourites_recipe from being saved:</h2>

      <ul>
      <% @favourites_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.number_field :recipe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites_recipes/edit.html.erb
<h1>Editing Favourites Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @favourites_recipe %> |
<%= link_to 'Back', favourites_recipes_path %>

app/views/favourites_recipes/index.html.erb
<% current_user.favourites.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= image_tag recipe.image.url(:medium) %>
            <h2><%= link_to recipe.title, recipe %></h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/favourites_recipes/new.html.erb
<h1>New Favourites Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', favourites_recipes_path %>

app/views/favourites_recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				%p
					Category 
					= Category.find(@recipe.category_id).name if @recipe.category_id != nil 
				%p
					Submitted by
					= @recipe.user.email

	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Directions
				%ul
					- @recipe.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in? 
				- if current_user.email == @recipe.user.email
					= link_to "Edit", edit_recipe_path, class: "btn btn-default"
					= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"
				- else
					= link_to "unfavorite",   favourite_recipe_path(@recipe, type: "unfavorite"), method: :put, class: "btn btn-default"
					//= link_to "Add To Favourite", favourites_recipes_path, method: :create, class: "btn btn-default"