config/routes.rb
Rails.application.routes.draw do

  	resources :favourites_recipes
  	resources :user_recipes
  	resources :categories
	devise_for :users
	resources :recipes

	resources :recipes do
	  put :favourite, on: :member
	end

	root "recipes#index"
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title RecipeBox
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Recipe Box", root_path
      .searchForm
        = form_tag recipes_path, :method => 'get' do
          = text_field_tag :search, params[:search], placeholder: "Search"
          = submit_tag "Search", :name => nil

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Choose Category", categories_path
          %li= link_to "My Recipes", user_recipes_path
          %li= link_to "My Favourite Recipes", favourites_recipes_path
          %li= link_to "New Recipe", new_recipe_path
          %li= link_to "Sign out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"}
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Choose Category", categories_path
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"
    = yield
  .footer
    - if user_signed_in?
      You are signed in as 
      = current_user.email
    - else
      Recipe Box